// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiHtoKx7X6NqQzwB0EncIqMSkd-ZvzsPA',
    appId: '1:1019134842060:web:5bac27bec5c000bf9d1e69',
    messagingSenderId: '1019134842060',
    projectId: 'umbrella-jump',
    authDomain: 'umbrella-jump.firebaseapp.com',
    storageBucket: 'umbrella-jump.appspot.com',
    measurementId: 'G-36L94E0GJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB68CpJyKhFqhXdhmO4AWzdZ9ODIyqcdGw',
    appId: '1:1019134842060:android:2d92638f4f60790e9d1e69',
    messagingSenderId: '1019134842060',
    projectId: 'umbrella-jump',
    storageBucket: 'umbrella-jump.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_JnrGpiksOjQtkFnvUM7Ftiq2qY1M51k',
    appId: '1:1019134842060:ios:6bd8fe43ac92b7069d1e69',
    messagingSenderId: '1019134842060',
    projectId: 'umbrella-jump',
    storageBucket: 'umbrella-jump.appspot.com',
    iosClientId:
        '1019134842060-7ujlanurco1cc7v2pvcrakdhv9ma8g3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodleDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_JnrGpiksOjQtkFnvUM7Ftiq2qY1M51k',
    appId: '1:1019134842060:ios:2fa295f5097f52cc9d1e69',
    messagingSenderId: '1019134842060',
    projectId: 'umbrella-jump',
    storageBucket: 'umbrella-jump.appspot.com',
    iosClientId:
        '1019134842060-tjmqgmkh5d1o79t14o4fb7rt8e651d8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodleDash.RunnerTests',
  );
}
